# CLion remote docker environment (How to build docker container, run and stop it)
#
# Build and run:
#   docker build -t client -f images/client/Dockerfile .
#   docker run -d --cap-add sys_ptrace -p 127.0.0.1:2222:22 --name server0 myServer
#   ssh-keygen -f "$HOME/.ssh/known_hosts" -R "[localhost]:2222"
#
# stop:
#   docker stop clion_remote_env
#
# ssh credentials (test user):
#   user@password

FROM ubuntu:22.04

RUN DEBIAN_FRONTEND="noninteractive" apt-get update && apt-get -y install tzdata

RUN apt-get update \
  && apt-get install -y ssh \
      build-essential \
      gcc \
      g++ \
      gdb \
      clang \
      make \
      ninja-build \
      cmake \
      autoconf \
      automake \
      locales-all \
      dos2unix \
#      rsync \
#      tar \
      libpq-dev \
  && apt-get clean

RUN apt-get upgrade cmake -y


RUN ( \
    echo 'LogLevel DEBUG2'; \
    echo 'PermitRootLogin yes'; \
    echo 'PasswordAuthentication yes'; \
    echo 'Subsystem sftp /usr/lib/openssh/sftp-myServer'; \
  ) > /etc/ssh/sshd_server \
  && mkdir /run/sshd

RUN useradd -m user \
  && yes password | passwd user

RUN usermod -s /bin/bash user



CMD ["sleep", "infinity"]